/** Renders a <datalist> from the shared option data, keyed by id.
 *  Replaces itself with the real element so inputs can still target it
 *  via the ordinary `list="dl-x"` attribute.
 *  Usage: <option-list for="dl-damage"></option-list> */
export class OptionList extends HTMLElement {
  private readonly DATALISTS: Record<string, readonly string[]> = {
    "dl-class": [
      "Artificer",
      "Barbarian",
      "Bard",
      "Cleric",
      "Druid",
      "Fighter",
      "Monk",
      "Paladin",
      "Ranger",
      "Rogue",
      "Sorcerer",
      "Warlock",
      "Wizard",
    ],
    "dl-bg": [
      "Acolyte",
      "Charlatan",
      "Criminal",
      "Entertainer",
      "Folk Hero",
      "Guild Artisan",
      "Hermit",
      "Noble",
      "Outlander",
      "Sage",
      "Sailor",
      "Soldier",
      "Urchin",
    ],
    "dl-align": [
      "Lawful Good",
      "Neutral Good",
      "Chaotic Good",
      "Lawful Neutral",
      "True Neutral",
      "Chaotic Neutral",
      "Lawful Evil",
      "Neutral Evil",
      "Chaotic Evil",
    ],
    "dl-damage": [
      "Acid",
      "Bludgeoning",
      "Cold",
      "Fire",
      "Force",
      "Lightning",
      "Necrotic",
      "Piercing",
      "Poison",
      "Psychic",
      "Radiant",
      "Slashing",
      "Thunder",
    ],
    "dl-weapon": [
      "Unarmed Strike",
      "Club",
      "Dagger",
      "Greatclub",
      "Handaxe",
      "Javelin",
      "Light Hammer",
      "Mace",
      "Quarterstaff",
      "Sickle",
      "Spear",
      "Light Crossbow",
      "Dart",
      "Shortbow",
      "Sling",
      "Battleaxe",
      "Flail",
      "Glaive",
      "Greataxe",
      "Greatsword",
      "Halberd",
      "Lance",
      "Longsword",
      "Maul",
      "Morningstar",
      "Pike",
      "Rapier",
      "Scimitar",
      "Shortsword",
      "Trident",
      "War Pick",
      "Warhammer",
      "Whip",
      "Blowgun",
      "Hand Crossbow",
      "Heavy Crossbow",
      "Longbow",
      "Net",
    ],
    "dl-senses": [
      "Darkvision 60 ft",
      "Darkvision 120 ft",
      "Superior Darkvision 120 ft",
      "Blindsight 30 ft",
      "Blindsight 60 ft",
      "Tremorsense 60 ft",
      "Truesight 60 ft",
      "Devil's Sight 120 ft",
    ],
    "dl-resist": [
      "Acid",
      "Bludgeoning",
      "Cold",
      "Fire",
      "Force",
      "Lightning",
      "Necrotic",
      "Piercing",
      "Poison",
      "Psychic",
      "Radiant",
      "Slashing",
      "Thunder",
      "Nonmagical bludgeoning, piercing & slashing",
    ],
    "dl-immune": [
      "Acid",
      "Bludgeoning",
      "Cold",
      "Fire",
      "Force",
      "Lightning",
      "Necrotic",
      "Piercing",
      "Poison",
      "Psychic",
      "Radiant",
      "Slashing",
      "Thunder",
      "Blinded",
      "Charmed",
      "Deafened",
      "Frightened",
      "Grappled",
      "Incapacitated",
      "Paralyzed",
      "Petrified",
      "Poisoned (condition)",
      "Prone",
      "Restrained",
      "Stunned",
      "Unconscious",
      "Disease",
      "Magical sleep",
    ],
    "dl-item": [
      "Backpack",
      "Bedroll",
      "Rope (50 ft)",
      "Torch",
      "Rations (1 day)",
      "Waterskin",
      "Tinderbox",
      "Crowbar",
      "Grappling Hook",
      "Lantern (hooded)",
      "Oil (flask)",
      "Potion of Healing",
      "Spellbook",
      "Component Pouch",
      "Arcane Focus",
      "Holy Symbol",
      "Druidic Focus",
      "Healer's Kit",
      "Thieves' Tools",
      "Caltrops (bag of 20)",
      "Ball Bearings (bag of 1,000)",
      "Chain (10 ft)",
      "Hammer",
      "Piton",
      "Shovel",
      "Steel Mirror",
      "Manacles",
      "Explorer's Pack",
      "Dungeoneer's Pack",
      "Burglar's Pack",
      "Diplomat's Pack",
      "Priest's Pack",
      "Scholar's Pack",
      "Entertainer's Pack",
      "Arrows (20)",
      "Crossbow Bolts (20)",
      "Padded Armor",
      "Leather Armor",
      "Studded Leather Armor",
      "Hide Armor",
      "Chain Shirt",
      "Scale Mail",
      "Breastplate",
      "Half Plate",
      "Ring Mail",
      "Chain Mail",
      "Splint Armor",
      "Plate Armor",
      "Shield",
      "Club",
      "Dagger",
      "Handaxe",
      "Javelin",
      "Mace",
      "Quarterstaff",
      "Spear",
      "Light Crossbow",
      "Shortbow",
      "Battleaxe",
      "Glaive",
    ],
    "dl-school": [
      "Abjuration",
      "Conjuration",
      "Divination",
      "Enchantment",
      "Evocation",
      "Illusion",
      "Necromancy",
      "Transmutation",
    ],
    "dl-prof": [
      "Common",
      "Dwarvish",
      "Elvish",
      "Giant",
      "Gnomish",
      "Goblin",
      "Halfling",
      "Orc",
      "Abyssal",
      "Celestial",
      "Draconic",
      "Deep Speech",
      "Infernal",
      "Primordial",
      "Sylvan",
      "Undercommon",
      "Thieves' Cant",
      "Druidic",
      "Light Armor",
      "Medium Armor",
      "Heavy Armor",
      "Shields",
      "Simple Weapons",
      "Martial Weapons",
      "Padded Armor",
      "Leather Armor",
      "Studded Leather Armor",
      "Hide Armor",
      "Chain Shirt",
      "Scale Mail",
      "Breastplate",
      "Half Plate",
      "Ring Mail",
      "Chain Mail",
      "Splint Armor",
      "Plate Armor",
      "Club",
      "Dagger",
      "Greatclub",
      "Handaxe",
      "Javelin",
      "Light Hammer",
      "Mace",
      "Quarterstaff",
      "Sickle",
      "Spear",
      "Light Crossbow",
      "Dart",
      "Shortbow",
      "Sling",
      "Battleaxe",
      "Flail",
      "Glaive",
      "Greataxe",
      "Greatsword",
      "Halberd",
      "Lance",
      "Longsword",
      "Maul",
      "Morningstar",
    ],
  };

  connectedCallback() {
    const id = this.getAttribute("for");
    const options = id ? this.DATALISTS[id] : undefined;
    if (!id || !options) return;

    const opts = options.map((v) => `<option value="${v}"></option>`).join("");
    this.outerHTML = /*html*/ `<datalist id="${id}">${opts}</datalist>`;
  }
}
